<template>
  <pro-crud ref="proCrudRef" v-bind="proCrudBinding" />
</template>

<script lang="tsx" setup>
import { buildCrud } from '~/index'

const { proCrudBinding, proCrudRef } = buildCrud(() => {
  return {
    columns: [
      {
        label: '设备名称',
        prop: 'deviceName',
        type: 'text',
        search: { show: true },
      },
      {
        label: '设备显示名称',
        prop: 'showName',
        search: { show: false },
      },
      {
        label: '设备类型',
        prop: 'deviceType',
        type: 'text',
        search: { show: false },
      },
      {
        label: '设备状态',
        prop: 'deviceStatus',
        type: 'dict-select',
        search: { show: true },
        dict: {
          data: [
            { label: '离线', value: 0 },
            { label: '在线', value: 1 },
          ],
        },
      },
      {
        label: 'IP地址',
        prop: 'ip',
        search: { show: false },
      },
      {
        label: 'MAC地址',
        prop: 'mac',
        search: { show: false },
      },
      {
        label: '设备位置',
        prop: 'addr',
        search: { show: false },
      },
      {
        label: '所属分组',
        prop: 'regionName',
        search: { show: false },
      },
    ],

    operates: {
      columnProps: { width: 250 },
    },

    request: {
      // transformQuery(ctx) {
      //   const {
      //     query: {
      //       page: { pageNumber, pageSize },
      //     },
      //     form,
      //   } = ctx
      //   return { query: { pageSize, pageNumber, ...form } }
      // },
      async fetchPaginationData() {
        return {
          total: 46,
          rows: [
            {
              deviceId: 111,
              deviceName: '红楼二楼5',
              showName: '研学楼二楼03',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.12',
              mac: '6C-B1-58-A2-7A-11',
              regionName: '默认分组',
              addr: '北区',
              x3: '-13361.572',
              y3: '-11527.337',
              z3: '534.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 70,
              deviceName: '红楼一楼4',
              showName: '研学楼一楼02',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.15',
              mac: '6C-B1-58-A2-5E-27',
              regionName: '默认分组',
              addr: '北区',
              x3: '-11761.572',
              y3: '-10327.337',
              z3: '53.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 112,
              deviceName: '北区综合楼室内4',
              showName: '北区综合楼一楼西03',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.17',
              mac: '6C-B1-58-DE-BF-28',
              regionName: '默认分组',
              addr: '北区',
              x3: '-30096.912',
              y3: '-6238.675',
              z3: '136.75',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 71,
              deviceName: '红楼一楼5',
              showName: '研学楼一楼04',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.18',
              mac: '6C-B1-58-A2-7C-E1',
              regionName: '默认分组',
              addr: '北区',
              x3: '-12961.572',
              y3: '-10627.337',
              z3: '53.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 87,
              deviceName: '北区综合楼5',
              showName: '北区综合楼一楼东14',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.19',
              mac: '6C-B1-58-DE-BF-19',
              regionName: '默认分组',
              addr: '北区',
              x3: '-26554.211',
              y3: '-7016.175',
              z3: '136.75',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 69,
              deviceName: '红楼一楼3',
              showName: '研学楼一楼06',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.20',
              mac: '6C-B1-58-DE-EE-E0',
              regionName: '默认分组',
              addr: '北区',
              x3: '-14961.572',
              y3: '-11227.337',
              z3: '53.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 88,
              deviceName: '北区综合楼6',
              showName: '北区综合楼一楼东10',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.22',
              mac: '6C-B1-58-DE-C8-2E',
              regionName: '默认分组',
              addr: '北区',
              x3: '-23740.912',
              y3: '-9054.138',
              z3: '136.75',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 79,
              deviceName: '红楼三楼2',
              showName: '研学楼三楼05',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.23',
              mac: '6C-B1-58-A2-6A-60',
              regionName: '默认分组',
              addr: '北区',
              x3: '-14961.572',
              y3: '-11527.337',
              z3: '1034.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 78,
              deviceName: '红楼三楼1',
              showName: '研学楼三楼02',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.24',
              mac: '6C-B1-58-A2-5D-58',
              regionName: '默认分组',
              addr: '北区',
              x3: '-11761.572',
              y3: '-10327.337',
              z3: '1034.825',
              x2: null,
              y2: null,
              areaType: '0',
            },
            {
              deviceId: 89,
              deviceName: '北区综合楼7',
              showName: '北区综合楼一楼东09',
              deviceType: 'CEILINGMOUNTAP',
              deviceStatus: '在线',
              deviceModel: 'TL-AP1208GC-PoE/DC',
              ip: '192.168.120.25',
              mac: '6C-B1-58-DE-EF-04',
              regionName: '默认分组',
              addr: '北区',
              x3: '-18624.963',
              y3: '-9231.506',
              z3: '436.75',
              x2: null,
              y2: null,
              areaType: '0',
            },
          ],
          code: 200,
          msg: '查询成功',
        }
      },
      // transformResponse(ctx) {
      //   const { response } = ctx

      //   return {
      //     total: response.total,
      //     data: response.rows,
      //   }
      // },
    },
  }
})
</script>
