// Generated by 'unplugin-auto-import'
export {}
declare global {
  const DefaultFormFieldType: typeof import('../../lib/components/ProForm/constant')['DefaultFormFieldType']
  const DefaultPreserve: typeof import('../../lib/components/ProForm/constant')['DefaultPreserve']
  const ProComponents: typeof import('../../lib/index')['ProComponents']
  const ProForm: typeof import('../../lib/components/ProForm/index')['ProForm']
  const ProFormScopeKey: typeof import('../../lib/components/ProForm/constant')['ProFormScopeKey']
  const ProFormValueKey: typeof import('../../lib/components/ProForm/constant')['ProFormValueKey']
  const ProSelect: typeof import('../../lib/components/ProSelect/index')['ProSelect']
  const ShowButton: typeof import('../../lib/components/ProForm/constant')['ShowButton']
  const buildForm: typeof import('../../lib/components/ProForm/buildForm')['buildForm']
  const proRender: typeof import('../../lib/components/ProRender/ProRender.vue')['default']
  const useForm: typeof import('../../lib/components/ProForm/hooks')['useForm']
  const valueTypeMap: typeof import('../../lib/components/ProForm/type')['valueTypeMap']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly DefaultFormFieldType: UnwrapRef<typeof import('../../lib/components/ProForm/constant')['DefaultFormFieldType']>
    readonly DefaultPreserve: UnwrapRef<typeof import('../../lib/components/ProForm/constant')['DefaultPreserve']>
    readonly ProComponents: UnwrapRef<typeof import('../../lib/index')['ProComponents']>
    readonly ProForm: UnwrapRef<typeof import('../../lib/components/ProForm/index')['ProForm']>
    readonly ProFormScopeKey: UnwrapRef<typeof import('../../lib/components/ProForm/constant')['ProFormScopeKey']>
    readonly ProFormValueKey: UnwrapRef<typeof import('../../lib/components/ProForm/constant')['ProFormValueKey']>
    readonly ProSelect: UnwrapRef<typeof import('../../lib/components/ProSelect/index')['ProSelect']>
    readonly ShowButton: UnwrapRef<typeof import('../../lib/components/ProForm/constant')['ShowButton']>
    readonly buildForm: UnwrapRef<typeof import('../../lib/components/ProForm/buildForm')['buildForm']>
    readonly proRender: UnwrapRef<typeof import('../../lib/components/ProRender/ProRender.vue')['default']>
    readonly useForm: UnwrapRef<typeof import('../../lib/components/ProForm/hooks')['useForm']>
    readonly valueTypeMap: UnwrapRef<typeof import('../../lib/components/ProForm/type')['valueTypeMap']>
  }
}
